-- 동호회 개설 기능을 위한 Supabase 스키마 변경 기록
-- 현재 운영 DB에는 수동 반영되어 있으므로 다시 실행하지 않는다.

BEGIN;

-- visibility 컬럼 오탈자 수정
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'clubs'
          AND column_name = 'visibillity'
    )
    AND NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'clubs'
          AND column_name = 'visibility'
    )
    THEN
        ALTER TABLE public.clubs
        RENAME COLUMN visibillity TO visibility;
    END IF;
END
$$;

-- 작은따옴표까지 문자열로 저장된 기존 데이터 정리
UPDATE public.clubs
SET gender_rule = 'all'
WHERE gender_rule = '''all''';

UPDATE public.clubs
SET join_method = 'approval'
WHERE join_method = '''approval''';

UPDATE public.clubs
SET visibility = 'public'
WHERE visibility = '''public''';

UPDATE public.club_join_questions
SET question_type = 'text'
WHERE question_type = '''text''';

-- 정상적인 기본값 지정
ALTER TABLE public.clubs
    ALTER COLUMN gender_rule SET DEFAULT 'all',
    ALTER COLUMN join_method SET DEFAULT 'approval',
    ALTER COLUMN visibility SET DEFAULT 'public';

ALTER TABLE public.club_join_questions
    ALTER COLUMN question_type SET DEFAULT 'text';

-- 연령대와 운동 수준의 중복 저장 방지
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname =
              'club_age_groups_club_id_age_group_key'
          AND conrelid =
              'public.club_age_groups'::regclass
    )
    THEN
        ALTER TABLE public.club_age_groups
        ADD CONSTRAINT
            club_age_groups_club_id_age_group_key
        UNIQUE (club_id, age_group);
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname =
              'club_sport_levels_club_id_sport_id_sport_level_key'
          AND conrelid =
              'public.club_sport_levels'::regclass
    )
    THEN
        ALTER TABLE public.club_sport_levels
        ADD CONSTRAINT
            club_sport_levels_club_id_sport_id_sport_level_key
        UNIQUE (club_id, sport_id, sport_level);
    END IF;
END
$$;

-- 동호회 소개 키워드 테이블
CREATE TABLE IF NOT EXISTS public.club_intro_keywords (
    club_intro_keyword_id bigint
        GENERATED BY DEFAULT AS IDENTITY,

    club_id bigint NOT NULL,
    keyword varchar(50) NOT NULL,
    display_order integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone
        NOT NULL DEFAULT now(),

    CONSTRAINT club_intro_keywords_pkey
        PRIMARY KEY (club_intro_keyword_id),

    CONSTRAINT club_intro_keywords_club_id_fkey
        FOREIGN KEY (club_id)
        REFERENCES public.clubs (club_id)
        ON DELETE CASCADE,

    CONSTRAINT club_intro_keywords_club_id_keyword_key
        UNIQUE (club_id, keyword),

    CONSTRAINT club_intro_keywords_display_order_check
        CHECK (display_order >= 0)
);

-- 클라이언트의 무제한 직접 접근 차단
ALTER TABLE public.club_intro_keywords
ENABLE ROW LEVEL SECURITY;

-- 동호회 회원 역할값 정규화
UPDATE public.club_members
SET role = CASE role
    WHEN '동호회장' THEN 'owner'
    WHEN '운영진' THEN 'manager'
    WHEN '일반회원' THEN 'member'
    ELSE role
END
WHERE role IN (
    '동호회장',
    '운영진',
    '일반회원'
);

-- 동호회 회원 활동 상태값 정규화
UPDATE public.club_members
SET status = CASE status
    WHEN '활동중' THEN 'active'
    WHEN '비활동중' THEN 'inactive'
    WHEN '비활동' THEN 'inactive'
    WHEN '활동정지' THEN 'suspended'
    WHEN '탈퇴' THEN 'withdrawn'
    ELSE status
END
WHERE status IN (
    '활동중',
    '비활동중',
    '비활동',
    '활동정지',
    '탈퇴'
);

-- 신규 회원의 기본 역할과 상태
ALTER TABLE public.club_members
    ALTER COLUMN role SET DEFAULT 'member',
    ALTER COLUMN status SET DEFAULT 'active';

-- 동호회 이미지 Storage 버킷 생성 또는 설정 갱신
INSERT INTO storage.buckets (
    id,
    name,
    public,
    file_size_limit,
    allowed_mime_types
)
VALUES (
    'club-images',
    'club-images',
    true,
    5242880,
    ARRAY[
        'image/jpeg',
        'image/png',
        'image/webp'
    ]
)
ON CONFLICT (id)
DO UPDATE SET
    name = EXCLUDED.name,
    public = EXCLUDED.public,
    file_size_limit = EXCLUDED.file_size_limit,
    allowed_mime_types = EXCLUDED.allowed_mime_types;

-- 정책을 반복 적용할 때 발생할 이름 중복 방지
DROP POLICY IF EXISTS
    "Users can upload own club images"
ON storage.objects;

DROP POLICY IF EXISTS
    "Users can view own club images"
ON storage.objects;

DROP POLICY IF EXISTS
    "Users can update own club images"
ON storage.objects;

DROP POLICY IF EXISTS
    "Users can delete own club images"
ON storage.objects;

-- 자신의 UUID 폴더에만 업로드 가능
CREATE POLICY
    "Users can upload own club images"
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (
    bucket_id = 'club-images'
    AND (storage.foldername(name))[1] =
        (SELECT auth.uid())::text
);

-- 자신의 UUID 폴더에 있는 객체 정보 조회 가능
CREATE POLICY
    "Users can view own club images"
ON storage.objects
FOR SELECT
TO authenticated
USING (
    bucket_id = 'club-images'
    AND (storage.foldername(name))[1] =
        (SELECT auth.uid())::text
);

-- 자신의 UUID 폴더에 있는 이미지 수정 가능
CREATE POLICY
    "Users can update own club images"
ON storage.objects
FOR UPDATE
TO authenticated
USING (
    bucket_id = 'club-images'
    AND (storage.foldername(name))[1] =
        (SELECT auth.uid())::text
)
WITH CHECK (
    bucket_id = 'club-images'
    AND (storage.foldername(name))[1] =
        (SELECT auth.uid())::text
);

-- 자신의 UUID 폴더에 있는 이미지 삭제 가능
CREATE POLICY
    "Users can delete own club images"
ON storage.objects
FOR DELETE
TO authenticated
USING (
    bucket_id = 'club-images'
    AND (storage.foldername(name))[1] =
        (SELECT auth.uid())::text
);

COMMIT;