-- =========================================================
-- 반복일정 실제 활동일 및 날짜별 참석 투표 연결
--
-- 기존 호환성
-- 1. 기존 club_events 구조는 변경하지 않는다.
-- 2. event_votes.event_occurrence_id는 nullable이다.
-- 3. 기존 단일 일정 투표는 occurrence 없이 계속 사용한다.
-- =========================================================


-- ---------------------------------------------------------
-- 반복일정의 실제 활동일
-- ---------------------------------------------------------
CREATE TABLE IF NOT EXISTS
    public.club_event_occurrences
(
    event_occurrence_id bigint
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    event_id bigint NOT NULL,

    occurrence_date date NOT NULL,

    start_time time without time zone NOT NULL,

    end_time time without time zone,

    status text NOT NULL
        DEFAULT 'scheduled',

    created_at timestamp with time zone
        NOT NULL
        DEFAULT now(),

    updated_at timestamp with time zone
        NOT NULL
        DEFAULT now(),

    CONSTRAINT
        club_event_occurrences_event_id_fkey
        FOREIGN KEY (event_id)
        REFERENCES public.club_events(event_id)
        ON DELETE CASCADE,

    CONSTRAINT
        club_event_occurrences_status_check
        CHECK (
            status IN (
                'scheduled',
                'completed',
                'cancelled'
            )
        ),

    CONSTRAINT
        club_event_occurrences_time_check
        CHECK (
            end_time IS NULL
            OR end_time > start_time
        ),

    CONSTRAINT
        club_event_occurrences_event_date_time_key
        UNIQUE (
            event_id,
            occurrence_date,
            start_time
        ),

    CONSTRAINT
        club_event_occurrences_id_event_key
        UNIQUE (
            event_occurrence_id,
            event_id
        )
);

ALTER TABLE public.club_event_occurrences
ENABLE ROW LEVEL SECURITY;

-- ---------------------------------------------------------
-- 반복일정 조회용 인덱스
-- ---------------------------------------------------------
CREATE INDEX IF NOT EXISTS
    club_event_occurrences_event_date_idx
ON public.club_event_occurrences (
    event_id,
    occurrence_date,
    start_time
);


CREATE INDEX IF NOT EXISTS
    club_event_occurrences_date_status_idx
ON public.club_event_occurrences (
    occurrence_date,
    status
);


-- ---------------------------------------------------------
-- 참석 투표와 실제 활동일 연결
--
-- nullable이므로 기존 event_votes 행에는 영향이 없다.
-- ---------------------------------------------------------
ALTER TABLE public.event_votes
ADD COLUMN IF NOT EXISTS
    event_occurrence_id bigint;


-- ---------------------------------------------------------
-- event_votes와 occurrence 복합 FK
--
-- event_id까지 함께 검증하므로 다른 일정의 occurrence를
-- 잘못 연결하는 것을 방지한다.
-- ---------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname =
            'event_votes_occurrence_event_fkey'
    ) THEN
        ALTER TABLE public.event_votes
        ADD CONSTRAINT
            event_votes_occurrence_event_fkey
        FOREIGN KEY (
            event_occurrence_id,
            event_id
        )
        REFERENCES public.club_event_occurrences (
            event_occurrence_id,
            event_id
        )
        ON DELETE CASCADE;
    END IF;
END
$$;


-- ---------------------------------------------------------
-- occurrence별 투표 조회 인덱스
-- ---------------------------------------------------------
CREATE INDEX IF NOT EXISTS
    event_votes_event_occurrence_id_idx
ON public.event_votes (
    event_occurrence_id
);


-- ---------------------------------------------------------
-- 하나의 실제 활동일에는 참석 투표를 하나만 허용
--
-- 일반 투표에는 영향을 주지 않고 attendance만 제한한다.
-- ---------------------------------------------------------
CREATE UNIQUE INDEX IF NOT EXISTS
    event_votes_attendance_occurrence_uidx
ON public.event_votes (
    event_occurrence_id
)
WHERE (
    vote_type = 'attendance'
    AND event_occurrence_id IS NOT NULL
);


-- ---------------------------------------------------------
-- 테이블 및 컬럼 설명
-- ---------------------------------------------------------
COMMENT ON TABLE
    public.club_event_occurrences
IS
    '반복일정에서 생성된 실제 활동 날짜';

COMMENT ON COLUMN
    public.club_event_occurrences.event_id
IS
    '반복일정 원본 club_events.event_id';

COMMENT ON COLUMN
    public.event_votes.event_occurrence_id
IS
    '반복일정의 특정 실제 활동일. 기존 단일 일정 투표는 NULL';